### ISSUE TITLE
Does not seem to be working?

### ISSUE THREAD

**Issue by leet0rz** [samyeyo/rtc#4]
Just downloaded and test it on a simple hello world lua script, it creates the .exe file but does not print hello world in the terminal when I run the .exe it made.

I basically did `rtc hw.lua` and it made hw.exe but nothing comes from it when executed.

**Comment by samyeyo** [comment]
Did you put the `lua54.dll` runtime library along with the generated executable ?

**Comment by leet0rz** [comment]
> Did you put the `lua54.dll` runtime library along with the generated executable ?

That works, but wasn't this suppose to be a standalone .exe creator? Is it possible to have it do that automatically every time I try to run RTC and then run the file? A bit annoying having to bring and copy the .dll file everywhere I try to turn lua files into exe. Thanks :)

**Comment by leet0rz** [comment]
> > Did you put the `lua54.dll` runtime library along with the generated executable ?
> 
> That works, thanks. However I thought this was suppose to be a standalone .exe file creator? Is it possible to have it do that automatically every time I try to run RTC and then run the file? A bit annoying having to bring and copy the .dll file everywhere I try to turn lua files into exe. Thanks :)

**Comment by samyeyo** [comment]
Lua runtime is designed to be used with this dll.

You can use `rtc` with the -s switch to build a static executable that won't need the Lua54.dll but at a coast : you will not be able to use binary modules.

**Comment by leet0rz** [comment]
> Lua runtime is designed to be used with this dll.
> 
> You can use `rtc` with the -s switch to build a static executable that won't need the Lua54.dll but at a coast : you will not be able to use binary modules.

I see,  When you are referring to binary modules, could you give me an example of something that would not work? Are you referring to requiring things and it not existing later because the .exe without dll can't find it or am I mistaken? Thanks.

**Comment by samyeyo** [comment]
Lua binary modules depends on `Lua54.dll`, so it's needed when you need to use them. 

As a side note, mixing the Lua runtime library with the static one in the static executable may crash the program as the C runtime library won't share the same memory space.
